# Generated by Django 2.0.4 on 2018-04-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ans',
            field=models.CharField(default='ans', max_length=200),
            preserve_default=False,
        ),
    ]
