# Generated by Django 2.0.4 on 2018-04-12 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_auto_20180408_1905'),
        ('topic', '0004_auto_20180408_2215'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLanguageSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Language')),
            ],
        ),
        migrations.CreateModel(
            name='JobTopicSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic')),
            ],
        ),
    ]
