# Generated by Django 2.0.4 on 2018-04-09 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_languagerating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagerating',
            old_name='Language',
            new_name='language',
        ),
    ]
