# Generated by Django 2.0.4 on 2018-04-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_topicrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengetopic',
            name='challenge',
            field=models.ManyToManyField(related_name='challenge', to='challenge.Challenge'),
        ),
        migrations.AlterField(
            model_name='challengetopic',
            name='topic',
            field=models.ManyToManyField(related_name='topic', to='topic.Topic'),
        ),
    ]
