# Generated by Django 2.0.4 on 2018-04-12 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_challenge_ans'),
        ('topic', '0004_auto_20180408_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengetopic',
            name='challenge',
        ),
        migrations.AddField(
            model_name='challengetopic',
            name='challenge',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='challenge.Challenge'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='challengetopic',
            name='topic',
        ),
        migrations.AddField(
            model_name='challengetopic',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='topic.Topic'),
            preserve_default=False,
        ),
    ]
